### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by glouppe** [diana-hep/carl#14]
I have not written a single line of documentation so far, except what can be found within the notebooks. We should fix that as soon as possible before the codebase grows to be too large :)

**Comment by glouppe** [comment]
https://github.com/BurntSushi/pdoc seems like a nice tool for generating static documentation.

**Comment by cranmer** [comment]
interesting. It seems like it's easier to get started with at least. Could add or switch to sphinx if we are not happy with it.

**Comment by glouppe** [comment]
The static documentation is now automatically generated and deployed upon commit on master.

It lives at http://diana-hep.org/carl/ :)

Next step is to fill in all the missing docstrings.

**Comment by glouppe** [comment]
There are some issues with formatting of docstrings, I'll investigate.

**Comment by glouppe** [comment]
Almost there! The only piece missing now is the documentation for `carl.distributions`.

**Comment by glouppe** [comment]
Done :)

**Comment by cranmer** [comment]
Nice work!
