### ISSUE TITLE
Cases p_i == p_i in Decomposed Ratios

### ISSUE THREAD

**Issue by jgpavez** [diana-hep/carl#16]
[Here](https://github.com/diana-hep/carl/blob/master/carl/ratios/cc.py) you do 
`                       p_num = cal_num.pdf(p, **kwargs)
                        p_den = cal_den.pdf(p, **kwargs)
                        mask = p_num != p_den
                        r[mask] += p_num[mask] / p_den[mask]
                        r[~mask] += 1.0
`
I think this is done in order to consider the cases p_i/p_i. The problem is that those are not the only cases in which p_num == p_den.

Consider for example areas in which p_num and p_den are both zeros due to lack of statistics .. on those cases the ratio should be 0. 
Maybe it would be better to consider the cases p_i == p_i even earlier in the computation in order to avoid calling cal_num.pdf and save some computation time.

**Comment by glouppe** [comment]
> Maybe it would be better to consider the cases p_i == p_i even earlier in the computation in order to avoid calling cal_num.pdf and save some computation time.

There are shortcuts like these implemented within `DecomposedRatio`

**Comment by jgpavez** [comment]
oh, yes you are right, I just saw it ... still maybe the mask is problematic in cases in which both distributions are zero due to lack of statistics.

**Comment by glouppe** [comment]
> still maybe the mask is problematic in cases in which both distributions are zero due to lack of statistics.

I am not sure about the semantics of setting the ratio to 0. Why would it be more correct than 1? The later amounts to say that x is as likely to have been generated from either distributions, while the former states that it should have been generated from the denominator.
