### ISSUE TITLE
Digital Object Identifier (DOI) to reference carl in papers

### ISSUE THREAD

**Issue by kreczko** [diana-hep/carl#24]
Dear developers,

I know the project is still in its early stages, but it might be good to consider a DOI service early.
https://zenodo.org/ provides integration with github and will produce a DOI automatically for each release created after the registration. This DOI can be included as a badge in your README as it is currently done with CI & coverage.

**Comment by glouppe** [comment]
>  automatically for each release created after the registration

Does it? Last time I tried I had to make a new Zenodo record for every new release :/

**Comment by glouppe** [comment]
But other than I agree, we should soon make a first 0.1 release.

**Comment by kreczko** [comment]
I was convinced it does. At least this is stated on their homepage:

> 1 Flip the switch

> Select the repository you want to preserve, and toggle the switch below to turn on automatic preservation of your software.
> 
> 2 Create a release
> Go to GitHub and create a release. Zenodo will automatically download a .zip-ball of all new releases and register a DOIs for them.
>
> 3 Get the badge
> After your first release, a DOI badge that you can include in GitHub README will appear next to your repository below.

Looking at my repositories I do see some inconsistencies. Zenodo seems to create a DOI **only for releases based on the master branch.**

**Comment by cranmer** [comment]
See https://github.com/JuliaLang/julia/issues/11990

Zenodo DOI versioning wasn't there very recently, but Lars says it is
almost ready

**Comment by glouppe** [comment]
Closing this, as we minted a DOI at https://zenodo.org/record/47798
