### ISSUE TITLE
Add negative log likelihood ratio to API

### ISSUE THREAD

**Issue by cranmer** [diana-hep/carl#31]
in common usage we will want to evaluate the - log likelihood ratio
```
    # Evaluate log-likelihood ratio
    r = ratio.predict(X_true, log=True)
    value = -np.sum(r[np.isfinite(r)])
```
can we add this directly to the API? maybe `nllr`?

That's a place it would be good to have a warning for the `isinf`

**Comment by glouppe** [comment]
Done in c4b54c0a4faeaa9a5a8323f77cacf77d353b94ca
