### ISSUE TITLE
Unify calibrators under a common interface

### ISSUE THREAD

**Issue by glouppe** [diana-hep/carl#37]
`carl.learning.CalibratedClassifierCV` currently supports calibration methods each implemented with a distinct API. It would be good to unify those under a same interface (à la IsotonicRegression as in scikit-learn) to simplify the codebase.

**Comment by cranmer** [comment]
+1

also, we should be able to wrap truth pdfs as classifiers. Then one could study effect of the calibration with finite samples when the classifier is exact.  (similar to the study of well-trained, poorly calibrated and well-trained, well-calibrated, but with a perfect classifier).
