### ISSUE TITLE
ability for CalibratedClassifier to correct for unbalanced class weights

### ISSUE THREAD

**Issue by cranmer** [diana-hep/carl#44]
If we have many more examples from p0 than p1, then the optimal score has factors from the sample weight / sample prior. This leads to strongly peaked score distribution. If we could correct for that easily then the histogram and kde calibration would be easier

**Comment by glouppe** [comment]
Agreed, but I would enforce that at the level of the ratio.

**Comment by glouppe** [comment]
Fixed in f32c978fe354099e2256d95fd7c3c526bf4f8c27
