### ISSUE TITLE
Export notebooks to markdown and automatically append to documentation

### ISSUE THREAD

**Issue by glouppe** [diana-hep/carl#49]
Would be super nice to have the notebooks in `examples` to be automatically exported to markdown and added to the static documentation, everytime it is deployed. 

Should not be that difficult, but requires a bit of fiddling around.

**Comment by cranmer** [comment]
We can do this with pelican.

**Comment by glouppe** [comment]
Bim! Notebooks are now automatically deployed as well. See e.g. http://diana-hep.org/carl/notebooks/Parameterized%20inference%20from%20multidimensional%20data.html

**Comment by cranmer** [comment]
Pretty!

Do you need to do anything beyond put it in the notebooks/ part of the repository?

Kyle

**Comment by glouppe** [comment]
Nope, nothing else. Notebooks are automatically converted to Markdown using `jupyter nbconvert` and then inserted back when building the documentation with `pdoc`.
