### ISSUE TITLE
Agree on conventions for defining the ratio r(x)

### ISSUE THREAD

**Issue by glouppe** [diana-hep/carl#5]
To avoid confusions, we should decide on naming convetions when defining the density ratio r(x). 

Options includes:
- r(x) = p0(x) / p1(x)
- r(x) = p1(x) / p0(x)
- r(x) = p_num(x) / p_den(x)

I started using the last convention in `carl.ratios`, but this should be extended also to the notebook example. 

What is your opinion?

**Comment by glouppe** [comment]
Also, when directly fitting a ratio from data, as in `ratio.fit(X, y)`, the `y` values should encode which samples correspond to the numerator and which samples correspond to the numerator. Right now, `X[y == 0]` is for the numerator and `X[y == 1]` for the denominator, but this can be changed.

**Comment by glouppe** [comment]
Similarly, we should agree on whether `s(x)` means `clf.predict_proba(x)[:, 0]` or `clf.predict_proba(x)[:, 1]`. Right now it is defined as `clf.predict_proba(x)[:, 0]` in the code.

**Comment by cranmer** [comment]
I would try to stay consistent with 1506.02169 just to avoid that confusion.
There p0 is in the numerator for the ratio and consistent with `s(x)` meaning `clf.predict_proba(x)[:, 0]`.

**Comment by glouppe** [comment]
Fine with me, since this is the solution requiring the least amount of changes on my side :)

**Comment by jgpavez** [comment]
maybe when fitting an option allowing to fit the denominator could be useful. you only need to invert the ratios so it will not need many changes on the code

**Comment by glouppe** [comment]
Closing.

We go for `r(x) = p0(x) / p1(x)` and `s(x) = clf.predict_proba(x)[:, 0]`.
